<?php

// Emoji => Font Awesome 6 (free, solid) icon. Value is "fa-name" or "fa-name|#color".
// Used by the static view converter and by the runtime swapper in
// resources/views/partials/emoji-icons.blade.php.
return [
    '🏠' => 'fa-house', '🏡' => 'fa-house', '🏢' => 'fa-building', '🏨' => 'fa-hotel', '🏙' => 'fa-city',
    '🏫' => 'fa-school', '🏥' => 'fa-hospital', '🏦' => 'fa-building-columns', '🚇' => 'fa-train-subway',
    '🚆' => 'fa-train', '✈' => 'fa-plane', '🚗' => 'fa-car', '🚓' => 'fa-car-side', '🛍' => 'fa-bag-shopping',
    '📍' => 'fa-location-dot', '🗺' => 'fa-map', '🧭' => 'fa-compass', '🌐' => 'fa-globe',
    '📞' => 'fa-phone', '📱' => 'fa-mobile-screen', '📲' => 'fa-mobile-screen-button', '📵' => 'fa-phone-slash',
    '☎' => 'fa-phone', '💬' => 'fa-comment-dots', '📧' => 'fa-envelope', '✉' => 'fa-envelope', '📬' => 'fa-envelope-open',
    '📢' => 'fa-bullhorn', '🔔' => 'fa-bell', '🔇' => 'fa-volume-xmark',
    '⚠' => 'fa-triangle-exclamation', '🚨' => 'fa-triangle-exclamation', '❌' => 'fa-circle-xmark',
    '✅' => 'fa-circle-check', '☑' => 'fa-square-check', '💯' => 'fa-circle-check', '❓' => 'fa-circle-question',
    '⛔' => 'fa-ban', '🚫' => 'fa-ban', '➕' => 'fa-plus',
    '💰' => 'fa-sack-dollar', '💵' => 'fa-money-bill-wave', '💲' => 'fa-dollar-sign', '🪙' => 'fa-coins',
    '💳' => 'fa-credit-card', '🧾' => 'fa-receipt', '💎' => 'fa-gem',
    '⏳' => 'fa-hourglass-half', '⏰' => 'fa-clock', '⏱' => 'fa-stopwatch', '⏸' => 'fa-pause', '▶' => 'fa-play',
    '📅' => 'fa-calendar-days', '📆' => 'fa-calendar-days',
    '📄' => 'fa-file-lines', '📃' => 'fa-file-lines', '📋' => 'fa-clipboard-list', '📝' => 'fa-pen-to-square',
    '✏' => 'fa-pencil', '✍' => 'fa-signature', '📜' => 'fa-scroll', '📘' => 'fa-book', '📚' => 'fa-book',
    '📂' => 'fa-folder-open', '🗄' => 'fa-box-archive', '📌' => 'fa-thumbtack',
    '👤' => 'fa-user', '👨' => 'fa-user', '👩' => 'fa-user', '🧑' => 'fa-user', '👥' => 'fa-users', '👯' => 'fa-user-group',
    '🤝' => 'fa-handshake', '🙏' => 'fa-hands-praying', '👋' => 'fa-hand', '👍' => 'fa-thumbs-up', '👎' => 'fa-thumbs-down',
    '👁' => 'fa-eye', '🚶' => 'fa-person-walking', '🤖' => 'fa-robot', '🥶' => 'fa-face-frown', '😢' => 'fa-face-frown',
    '🔒' => 'fa-lock', '🔓' => 'fa-lock-open', '🔐' => 'fa-lock', '🔏' => 'fa-lock', '🛡' => 'fa-shield-halved',
    '🔍' => 'fa-magnifying-glass', '🗑' => 'fa-trash-can', '⚡' => 'fa-bolt', '🔥' => 'fa-fire', '✨' => 'fa-wand-magic-sparkles',
    '⭐' => 'fa-star|#f59e0b', '🌟' => 'fa-star|#f59e0b', '🏆' => 'fa-trophy', '🎯' => 'fa-bullseye', '🎉' => 'fa-champagne-glasses',
    '🎁' => 'fa-gift', '🎓' => 'fa-graduation-cap', '🚀' => 'fa-rocket', '💡' => 'fa-lightbulb', '🆕' => 'fa-certificate',
    '🔴' => 'fa-circle|#ef4444', '🟠' => 'fa-circle|#f97316', '🟡' => 'fa-circle|#eab308', '🟢' => 'fa-circle|#22c55e',
    '🔵' => 'fa-circle|#3b82f6', '🟣' => 'fa-circle|#8b5cf6',
    '📊' => 'fa-chart-column', '📈' => 'fa-chart-line', '🔄' => 'fa-rotate', '🔁' => 'fa-repeat',
    '📤' => 'fa-arrow-up-from-bracket', '📥' => 'fa-inbox', '⬇' => 'fa-arrow-down', '💾' => 'fa-floppy-disk',
    '🔗' => 'fa-link', '🆔' => 'fa-id-badge', '🪪' => 'fa-id-card', '🖨' => 'fa-print', '📸' => 'fa-camera', '📷' => 'fa-camera',
    '🚩' => 'fa-flag', '🏁' => 'fa-flag-checkered', '🛠' => 'fa-screwdriver-wrench', '🔧' => 'fa-wrench', '⚙' => 'fa-gear',
    '🛏' => 'fa-bed', '🛋' => 'fa-couch', '🪑' => 'fa-chair', '🚪' => 'fa-door-open', '🧳' => 'fa-suitcase-rolling',
    '💼' => 'fa-briefcase', '🧪' => 'fa-flask', '🧹' => 'fa-broom', '🚿' => 'fa-shower', '💧' => 'fa-droplet',
    '❄' => 'fa-snowflake', '📶' => 'fa-wifi', '📹' => 'fa-video', '🍱' => 'fa-utensils', '🍽' => 'fa-utensils',
    '🥣' => 'fa-bowl-food', '🍛' => 'fa-bowl-rice', '🐾' => 'fa-paw', '🔋' => 'fa-battery-full', '🅿' => 'fa-square-parking',
    '🏋' => 'fa-dumbbell', '♨' => 'fa-hot-tub-person', '🧊' => 'fa-temperature-low', '🛵' => 'fa-motorcycle',
    '🧼' => 'fa-soap', '🛡' => 'fa-shield-halved', '🔌' => 'fa-plug', '🪟' => 'fa-window-maximize', '🍳' => 'fa-kitchen-set',
    '🌙' => 'fa-moon', '☀' => 'fa-sun', '🌿' => 'fa-leaf', '🚌' => 'fa-bus', '🛒' => 'fa-cart-shopping', '☕' => 'fa-mug-hot',
    '📺' => 'fa-tv', '🧺' => 'fa-shirt', '🛗' => 'fa-elevator', '🗄' => 'fa-box-archive', '♥' => 'fa-heart', '↩' => 'fa-rotate-left',
];
