<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a1a; margin: 40px; line-height: 1.6; }
    h1 { font-size: 18px; text-align: center; margin-bottom: 4px; }
    h2 { font-size: 13px; margin-top: 20px; margin-bottom: 6px; }
    .subtitle { text-align: center; font-size: 11px; color: #666; margin-bottom: 24px; }
    .section { margin-bottom: 12px; }
    .label { font-weight: bold; }
    .details-table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
    .details-table td { padding: 5px 8px; border: 1px solid #ddd; }
    .details-table td:first-child { font-weight: bold; width: 40%; background: #f9f9f9; }
    .terms { margin-top: 16px; }
    .terms p { margin-bottom: 8px; }
    .signature-block { margin-top: 60px; border-top: 1px solid #ccc; padding-top: 12px; }
    .sig-line { border-bottom: 1px solid #333; width: 260px; display: inline-block; margin-bottom: 4px; }
    .footer { margin-top: 40px; font-size: 10px; color: #888; text-align: center; }
</style>
</head>
<body>

<h1>Rental Agreement</h1>
<div class="subtitle">Powered by Pizi.in | Digital PG Management Platform</div>

<table class="details-table">
    <tr><td>Tenant Name</td><td>{{ $user->name }}</td></tr>
    <tr><td>Tenant Phone</td><td>{{ $user->phone }}</td></tr>
    <tr><td>Tenant Email</td><td>{{ $user->email ?? '—' }}</td></tr>
    @if($tenant && $tenant->property)
    <tr><td>Property</td><td>{{ $tenant->property->name }}</td></tr>
    <tr><td>Address</td><td>{{ $tenant->property->address_line ?? '—' }}</td></tr>
    <tr><td>Monthly Rent</td><td>₹{{ number_format($tenant->monthly_rent ?: ($tenant->property->rent_min ?? 0)) }}</td></tr>
    <tr><td>Security Deposit</td><td>₹{{ number_format($tenant->security_deposit ?: ($tenant->property->security_deposit ?? 0)) }}</td></tr>
    @else
    <tr><td>Property</td><td>To be confirmed by owner</td></tr>
    @endif
    <tr><td>Date</td><td>{{ now()->format('d M Y') }}</td></tr>
</table>

<div class="terms">
    <h2>Terms and Conditions</h2>
    <p><strong>1. Term:</strong> This agreement is valid from the date of move-in until either party provides notice as per the agreed notice period (standard: 30 days).</p>
    <p><strong>2. Rent:</strong> Tenant agrees to pay monthly rent by the date specified by the PG owner. Late payments may attract charges as per the owner's policy.</p>
    <p><strong>3. Security Deposit:</strong> Refundable at end of tenancy, subject to deductions for damages or dues as assessed by the PG owner.</p>
    <p><strong>4. House Rules:</strong> Tenant agrees to abide by house rules communicated by the PG owner (timings, guest policy, noise, cleanliness, etc.).</p>
    <p><strong>5. Conduct:</strong> Tenant will not sub-let, cause damage, or engage in illegal activity on the premises.</p>
    <p><strong>6. Termination:</strong> Either party may terminate with the agreed notice period. Deposit refund will follow the owner's standard process.</p>
    <p><strong>7. Platform Role:</strong> Pizi facilitates the connection between Tenant and Owner and is not a party to the tenancy itself. Disputes are to be resolved between Tenant and Owner directly, with Pizi providing reasonable assistance.</p>
    <p style="font-size:11px; color:#555;">By signing this document with Aadhaar eSign, the tenant confirms they have read and agreed to all above terms. This document is legally binding under the Information Technology Act, 2000.</p>
</div>

<div class="signature-block">
    <p><span class="sig-line">&nbsp;</span></p>
    <p><strong>Tenant Signature</strong> (via Aadhaar eSign)</p>
    <p>Name: {{ $user->name }}</p>
    <p>Date: {{ now()->format('d M Y') }}</p>
</div>

<div class="footer">
    Generated by Pizi.in | Agreement ID: {{ $tenant->id ?? 'N/A' }} | {{ now()->format('d M Y H:i') }}
</div>

</body>
</html>